### ISSUE TITLE
[meta] frontend change list to accommodate multiple products

### ISSUE THREAD

**Issue by hamilton** [mozilla/glam#569]
After trying #558, here is a list of changes that will be needed to accommodate other projects more generally. This is not an exhaustive list but should be a great start. The problem areas are:

- `store.js` – we need to remove a lot of Firefox-specific logic. To achieve this, we may have to refactor how we instantiate the store and how we request data. These will be welcome changes.
- `probe-utils.js` – this has been drastically simplified over the past few weeks, but more work is to be done to move Firefox-specific functionality out of here and into the product config files
- throughout components, assumptions are made that are Firefox-specific. It should be straightforward to generalize these.

## `src/utils/probe-utils.js`
- [x] for `getProbeViewType`, each one of these checks should be per-product and in a product config file in `src/config/<product>`
- [x] each transformation function (like `transformQuantileResponse`) needs to remove the conflation of `build_id` with date. We use a function, `fullBuildIDToDate`, on build ids, but most build ids outside of Firefox will NOT be dates.
- [x] there will need to be product-specific `updateStoreAfterDataIsReceived` callbacks. Right now this one is Firefox-specific.

## `src/state/store.js`
- [x] `getParamsForDataAPI` and `getParamsForQueryString` – needs to be made product-specific and in config files.
- [x] initial state has a lot of hard-coded stuff in it that is firefox-specific. This needs to be handled better than it is now. It's possible that store instantiation shouldn't actually happen at the module import level but in a function somewhere. This will need to be re-thought.
- [x] All of the querystring-pulling functionality must be product-specific

## `src/routing/wrappers/Probe.svelte`
- [x] remove the need for `temporaryViewTypeStore` as a workaround.
- [x] make the details pane product-specific
- [ ] version markers should be product-specific

## `src/components/explore/ToplineRow.svelte`
- [x] remove the need for date-specific build ids

## `src/components/explore/BuildIDRollover.svelte`
- [x] the build id rollover should have slot props for however you want to format and shoudl probably be renamed to `BuildDateRollover.svelte` to more accurately reflect that build id and build date are two separate things

## querying issues
- [ ] we need to integrate a probe's metadata into the selector, since (for example) not all probes record in all Glean pings.

## error messages
- [x] we need to disambiguate _all_ 404s from firefox specific ones.

## search
- [x] search should be product-specific via PSS

**Comment by robhudson** [comment]
Opened issues for the last 2 items:
https://github.com/mozilla/glam/issues/955
https://github.com/mozilla/glam/issues/956
