### ISSUE TITLE
[meta] redesign the layout / styling of the frontend app bar / body

### ISSUE THREAD

**Issue by hamilton** [mozilla/glam#68]
When we made the choice to remove the left sidebar, we did the bare minimum to migrate the accordions on the left - they now live in the toolbar. The work is not, however complete. The layout will require some refactoring to work across the variety of viewport sizes we're likely to encounter. This will entail:

- [x] the body should have a max width of `1200px` and should be centered in the app. 1200px is the minimum width we are going to support. Further work might be done in the future to pare it down to ~900px, but this will entail making the details side bar transform into a drawer upon hitting the <1200px width. Doable w/ a combination of media queries and using `<svelte:window />`
- [x] the details view on the side should not have a white background – it should be floating text and information to the right of a body surface (which should be white)
- [x] the app bar will need to have its styling updated to fix weird spacing issues left over from quick refactor

This is almost entirely an exercise in css / design, so whomever takes this should be intimately familiar with our css params, grids, etc.

**Comment by hamilton** [comment]
@spasovski assigning you to this meta issue, since I believe you're already making a lot of the tweaks here.
